### ISSUE TITLE
access via context function

### ISSUE THREAD

**Issue by yakir12** [tk3369/ContextTracking.jl#12]
Awesome package, thank you.

I seem to do a lot of:
```julia
temp_variable = context()
thing_I_want_1 = c.data[:thing_I_want_1]
thing_I_want_2 = c.data[:thing_I_want_2]
thing_I_want_3 = c.data[:thing_I_want_3]
```
It would be more convenient to:
```julia
thing_I_want_1, thing_I_want_2, thing_I_want_3 = context(:thing_I_want_1, :thing_I_want_2, :thing_I_want_3)
```

**Comment by tk3369** [comment]
I'm glad that it's useful for you. 

Since `context.data` is just a dictionary, maybe you can do something like this?

```julia
x = (; context().data...)
```

Then, you can reference the variables like `x.thing1`, `x.thing2` etc?  

You can also do further destructuring as:
```julia
thing1, thing2, thing3 = x.thing1, x.thing2, x.thing3
```

**Comment by yakir12** [comment]
Perfect, thank you again!
