### ISSUE TITLE
Don't export a word like save

### ISSUE THREAD

**Issue by yakir12** [tk3369/ContextTracking.jl#14]
Many packages export the word `save`, yours too (https://github.com/tk3369/ContextTracking.jl/blob/9503f6d4f108d6c01c63939c744daece247c3aff/src/ContextTracking.jl#L9). This creates a conflict. Is it necessary in this case? It doesn't seem to be part of the API. I suggest un-exporting it.

**Comment by tk3369** [comment]
Resolved and a new version has been tagged.
